test_anagram (__main__.TestExercice) ... FAIL
test_doubles (__main__.TestExercice) ... FAIL
test_grades (__main__.TestExercice) ... FAIL
test_histogram (__main__.TestExercice) ... FAIL
test_order (__main__.TestExercice) ... FAIL

======================================================================
FAIL: test_anagram (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 40, in test_anagram
    'Erreur dans la vérification de l\'anagramme'
AssertionError: Lists differ: [False, False] != [True, False]

First differing element 0:
False
True

- [False, False]
+ [True, False] : Erreur dans la vérification de l'anagramme

======================================================================
FAIL: test_doubles (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 55, in test_doubles
    'Erreur dans les doublons'
AssertionError: Lists differ: [False, False] != [False, True]

First differing element 1:
False
True

- [False, False]
+ [False, True] : Erreur dans les doublons

======================================================================
FAIL: test_grades (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 69, in test_grades
    'Erreur dans les notes'
AssertionError: [{}] is not an instance of <class 'dict'> : First argument is not a dictionary

======================================================================
FAIL: test_histogram (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 84, in test_histogram
    'Erreur dans les histogrammes'
AssertionError: [({}, []), ({}, [])] is not an instance of <class 'dict'> : First argument is not a dictionary

======================================================================
FAIL: test_order (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 25, in test_order
    'Mauvais ordre'
AssertionError: Lists differ: [False, False] != [[-2, 1, 6, 9], ['2', 'a', 'hello']]

First differing element 0:
False
[-2, 1, 6, 9]

- [False, False]
+ [[-2, 1, 6, 9], ['2', 'a', 'hello']] : Mauvais ordre

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=5)
